sudo: false
language: node_js
node_js:
  - "8"
script:
  - npm run lint
  - npm test
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
